# Generated by Django 5.2.8 on 2026-01-17 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('bio', models.TextField()),
                ('past_work', models.TextField(help_text='Describe past accomplishments and projects')),
                ('ai_work_analysis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='manifestos/')),
                ('vision_summary', models.TextField(blank=True, null=True)),
                ('key_promises', models.TextField(blank=True, null=True)),
                ('ai_vision_analysis', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestos', to='candidates.candidate')),
            ],
        ),
    ]
