# Generated by Django 5.2.8 on 2026-01-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_is_active_candidate_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='province',
            field=models.CharField(choices=[('1', 'Koshi Province'), ('2', 'Madhesh Province'), ('3', 'Bagmati Province'), ('4', 'Gandaki Province'), ('5', 'Lumbini Province'), ('6', 'Karnali Province'), ('7', 'Sudurpashchim Province')], default='3', max_length=1),
        ),
    ]
