# Generated by Django 5.2.8 on 2026-01-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_querylog_researchanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
