# Generated by Django 5.2.8 on 2026-01-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_search_count_candidate_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
