# Generated by Django 5.2.8 on 2026-01-30 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_querylog_sentiment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('searches', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to='candidates.candidate')),
            ],
            options={
                'verbose_name_plural': 'Engagement Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
